### ISSUE TITLE
Installing on vagrant

### ISSUE THREAD

**Issue by 0x2F** [tylertreat/Comcast#29]
Linux precise32 3.2.0-23-generic-pae #36-Ubuntu SMP Tue Apr 10 22:19:09 UTC 2012 i686 i686 i386 GNU/Linux

vagrant@precise32:~$ go get github.com/tylertreat/comcast
 github.com/tylertreat/comcast/throttler
/usr/lib/go/src/pkg/github.com/tylertreat/comcast/throttler/throttler.go:160: undefined: bufio.NewScanner

**Comment by tylertreat** [comment]
What version of Go is this?

**Comment by 0x2F** [comment]
go version go1


Note that its Ubuntu.

**Comment by tylertreat** [comment]
Yeah, I don't think this will work with versions before 1.3.
